### ISSUE TITLE
The Jevois Pro claims to be 120 FPS, but no matter what I do, I can't get more than 33 fps.

### ISSUE THREAD

**Issue by DeusMos** [jevois/jevoispro-sdk#1]
The Jevois Pro claims to be 120 FPS, but no matter what I do, I can't get more than 33 fps.
https://www.jevoisinc.com/products/jevois-pro-deep-learning-smart-camera

I noticed that all other settings are commented out in the driver. 
fenix/linux/drivers/amlogic/isp_module/subdev/sensor/src/driver/sensor/IMX209_drv.c : supported_modes

Lines 96 - 361

Also, none of these modes are over 60Hz 

I see    
"http://jevois.org/doc/Camera_8C_source.html
// The IMX290 sensor only works well at native 1920x1080 with the JeVoisPro A311D ISP. So we always capture at 1080p
// and use crop/rescale in the ISP for other resolutions: "

Does this mean you have disabled all other sensor settings, and the sensor can't generate anything but 30fps?

What we need is an input for a model with shape (120,1980,3) @ 90-120 Hz

If the JevoisPro, can't run at over 33hz, I need to know so I can cancel this project before I waste more time and money on it.

**Comment by jevois** [comment]
We added support for 60fps and 120fps capture. 60fps works great, 120fps has some color issue where very bright highlights will turn pink/purple as opposed to saturated white. We assume this may come from the fact that the IMX290 sensor captures 10-bit at 120fps, but 12-bit at 30fps and 60fps, or it may be a lens issue as apparently some DSLR cameras have that problem as well under some conditions.

To select a mode, you will use ispsensorpreset in the global initscript.cfg of your JeVois-Pro camera. This will be available in JeVois 1.19.0 and we will send you a custom patch now.
